version: 2.1
jobs:
  compile:
   docker:
      - image: panchajanya1999/archlinux:latest
   steps:
      - run:
          command: |
            pacman -Syu --needed --noconfirm wget xmlto git zip
            git clone --depth=1 https://github.com/fredslbn/surya2.git -b main builder_kernel
            cd builder_kernel
            bash .circleci/surya.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
